# Horizontal Pod Autoscaler for API Gateway
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: cafe-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
# HPA for User Service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-hpa
  namespace: cafe-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service-deployment
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
# HPA for Customer Service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: customer-service-hpa
  namespace: cafe-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customer-service-deployment
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
# HPA for Menu Service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: menu-service-hpa
  namespace: cafe-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: menu-service-deployment
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
# Network Policy for micro-segmentation
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cafe-network-policy
  namespace: cafe-management
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: cafe-management
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: cafe-management
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
---
# Resource Quota for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cafe-resource-quota
  namespace: cafe-management
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
    services: "10"
    secrets: "5"
    configmaps: "5"
---
# Pod Disruption Budget for API Gateway
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  namespace: cafe-management
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-gateway
---
# Pod Disruption Budget for User Service
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: user-service-pdb
  namespace: cafe-management
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: user-service
---
# Pod Disruption Budget for Customer Service
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: customer-service-pdb
  namespace: cafe-management
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: customer-service
---
# Pod Disruption Budget for Menu Service
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: menu-service-pdb
  namespace: cafe-management
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: menu-service