# Namespace for cafe management system
apiVersion: v1
kind: Namespace
metadata:
  name: cafe-management
  labels:
    name: cafe-management
---
# ConfigMap for shared environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: cafe-config
  namespace: cafe-management
data:
  LOG_LEVEL: "info"
  NODE_ENV: "production"
  JWT_SECRET: "your-jwt-secret-here"
  JWT_REFRESH_SECRET: "your-jwt-refresh-secret-here"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
---
# Secret for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: cafe-secrets
  namespace: cafe-management
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded values
  mongodb-uri: bW9uZ29kYitzcnY6Ly91c2VybmFtZTpwYXNzd29yZEBjbHVzdGVyLm1vbmdvZGIubmV0L2NhZmVkYg==
  customer-db-uri: bW9uZ29kYitzcnY6Ly91c2VybmFtZTpwYXNzd29yZEBjbHVzdGVyLm1vbmdvZGIubmV0L2N1c3RvbWVyZGI=
  menu-db-uri: bW9uZ29kYitzcnY6Ly91c2VybmFtZTpwYXNzd29yZEBjbHVzdGVyLm1vbmdvZGIubmV0L21lbnVkYg==
---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: cafe-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: cafe-management
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
# API Gateway Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: cafe-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: cafe-management/api-gateway:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: cafe-config
              key: NODE_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: cafe-config
              key: LOG_LEVEL
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: cafe-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: cafe-config
              key: REDIS_PORT
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
# API Gateway Service
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: cafe-management
spec:
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
---
# User Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: cafe-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: cafe-management/user-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: cafe-config
              key: NODE_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: cafe-config
              key: LOG_LEVEL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: cafe-config
              key: JWT_SECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            configMapKeyRef:
              name: cafe-config
              key: JWT_REFRESH_SECRET
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: cafe-secrets
              key: mongodb-uri
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
# User Service
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: cafe-management
spec:
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
---
# Customer Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-deployment
  namespace: cafe-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: cafe-management/customer-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: cafe-config
              key: NODE_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: cafe-config
              key: LOG_LEVEL
        - name: CUSTOMER_DB_URI
          valueFrom:
            secretKeyRef:
              name: cafe-secrets
              key: customer-db-uri
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: cafe-secrets
              key: mongodb-uri
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
---
# Customer Service
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: cafe-management
spec:
  selector:
    app: customer-service
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
---
# Menu Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service-deployment
  namespace: cafe-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: menu-service
  template:
    metadata:
      labels:
        app: menu-service
    spec:
      containers:
      - name: menu-service
        image: cafe-management/menu-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          value: "3003"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: cafe-config
              key: NODE_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: cafe-config
              key: LOG_LEVEL
        - name: MENU_DB_URI
          valueFrom:
            secretKeyRef:
              name: cafe-secrets
              key: menu-db-uri
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: cafe-secrets
              key: mongodb-uri
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
---
# Menu Service
apiVersion: v1
kind: Service
metadata:
  name: menu-service
  namespace: cafe-management
spec:
  selector:
    app: menu-service
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003