# ArgoCD Installation Manifest
# This creates the namespace for ArgoCD installation
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
---
# ArgoCD Server Service Configuration
# This exposes the ArgoCD server as a LoadBalancer for easy access
apiVersion: v1
kind: Service
metadata:
  name: argocd-server-loadbalancer
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server