name: CI/CD Pipeline

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]

permissions:
    contents: read
    security-events: write
    actions: read
    packages: write

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    # Test and Lint
    test:
        name: Test and Lint
        runs-on: ubuntu-latest
        continue-on-error: true
        strategy:
            fail-fast: false
            matrix:
                service:
                    [
                        api-gateway,
                        user-service,
                        customer-service,
                        menu-service,
                        order-service,
                        payment-service,
                        inventory-service,
                        reservation-service,
                        notification-service,
                        report-service,
                    ]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"

            - name: Debug directory structure
              run: |
                  echo "Current working directory:"
                  pwd
                  echo "Repository root contents:"
                  ls -la
                  echo "Backend directory contents:"
                  ls -la Backend/ || echo "Backend directory not found"
                  echo "Service directories in Backend:"
                  ls -la Backend/ | grep -E "(api-gateway|user-service|customer-service|menu-service|order-service|payment-service|inventory-service|reservation-service|notification-service|report-service)" || echo "No service directories found"

            - name: Install dependencies for ${{ matrix.service }}
              run: |
                  cd Backend/${{ matrix.service }}
                  if [ -f package.json ]; then
                      echo "Installing dependencies for ${{ matrix.service }}"
                      npm install
                  else
                      echo "No package.json found for ${{ matrix.service }}"
                      exit 1
                  fi

            - name: Run linting for ${{ matrix.service }}
              run: |
                  cd Backend/${{ matrix.service }}
                  echo "Running linting for ${{ matrix.service }}"
                  npm run lint

            - name: Run tests
              run: |
                  cd Backend/${{ matrix.service }}
                  if npm test; then
                    echo "✅ Tests passed for ${{ matrix.service }}"
                  else
                    echo "⚠️  Some tests failed in ${{ matrix.service }}, but continuing..."
                  fi

            - name: Generate test coverage
              run: |
                  cd Backend/${{ matrix.service }}
                  if npm run test:coverage; then
                    echo "✅ Coverage generated for ${{ matrix.service }}"
                  else
                    echo "⚠️  Coverage generation failed for ${{ matrix.service }}, but continuing..."
                  fi

            - name: Upload coverage to Codecov
              if: success() || failure()
              uses: codecov/codecov-action@v3
              with:
                  file: Backend/${{ matrix.service }}/coverage/lcov.info
                  flags: ${{ matrix.service }}
                  name: ${{ matrix.service }}-coverage
                  fail_ci_if_error: false

    # Security Scanning
    security:
        name: Security Scan
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              with:
                  scan-type: "fs"
                  scan-ref: "."
                  format: "sarif"
                  output: "trivy-results.sarif"

            - name: Upload Trivy scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v3
              if: always()
              continue-on-error: true
              with:
                  sarif_file: "trivy-results.sarif"

            - name: Display Trivy results as summary
              if: always()
              run: |
                  echo "## Security Scan Summary" >> $GITHUB_STEP_SUMMARY
                  echo "Trivy vulnerability scan completed." >> $GITHUB_STEP_SUMMARY
                  if [ -f "trivy-results.sarif" ]; then
                    echo "✅ SARIF results generated successfully" >> $GITHUB_STEP_SUMMARY
                  else
                    echo "⚠️  SARIF results not found" >> $GITHUB_STEP_SUMMARY
                  fi

            - name: Run npm audit
              run: |
                  cd Backend
                  echo "## Security Audit Results" > audit-results.txt
                  for service in api-gateway user-service customer-service menu-service order-service payment-service inventory-service reservation-service notification-service report-service; do
                    if [ -d "$service" ] && [ -f "$service/package.json" ]; then
                      echo "### Auditing $service" >> audit-results.txt
                      cd "$service"
                      if npm audit --audit-level moderate >> ../audit-results.txt 2>&1; then
                        echo "✅ $service: No issues found" >> ../audit-results.txt
                      else
                        echo "⚠️  $service: Issues found (check above)" >> ../audit-results.txt
                      fi
                      cd ..
                    fi
                  done
                  echo "Security audit completed. Check audit-results.txt for details."
                  cat audit-results.txt

    # Build and Push Images
    build:
        name: Build and Push Images
        runs-on: ubuntu-latest
        needs: [test, security]
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        permissions:
            contents: read
            packages: write
        strategy:
            matrix:
                service:
                    [
                        api-gateway,
                        user-service,
                        customer-service,
                        menu-service,
                        order-service,
                        payment-service,
                        inventory-service,
                        reservation-service,
                        notification-service,
                        report-service,
                    ]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Convert repository name to lowercase
              id: repo-name
              run: |
                  REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')
                  echo "IMAGE_NAME_LOWER=$REPO_LOWER" >> $GITHUB_OUTPUT
                  echo "Repository name (lowercase): $REPO_LOWER"
                  echo "Service: ${{ matrix.service }}"
                  echo "Full image name will be: ${{ env.REGISTRY }}/$REPO_LOWER/${{ matrix.service }}"

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ steps.repo-name.outputs.IMAGE_NAME_LOWER }}/${{ matrix.service }}
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=sha,prefix=sha-
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: Backend/${{ matrix.service }}
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

    # Deploy to Staging
    deploy-staging:
        name: Deploy to Staging
        runs-on: ubuntu-latest
        needs: [build]
        if: github.ref == 'refs/heads/develop' && github.repository == 'MovinduSenura/Cafe-Management-System'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Staging Deployment (Manual)
              run: |
                  echo "Staging deployment would happen here"
                  echo "Build completed for commit: ${{ github.sha }}"
                  echo "Images tagged as: sha-${{ github.sha }}"
                  echo "To deploy manually:"
                  echo "   1. Configure kubectl for staging cluster"
                  echo "   2. Run: helm upgrade --install cafe-management-staging ./infrastructure/helm/cafe-management"

    # Deploy to Production  
    deploy-production:
        name: Deploy to Production
        runs-on: ubuntu-latest
        needs: [build]
        if: github.ref == 'refs/heads/main' && github.repository == 'MovinduSenura/Cafe-Management-System'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Production Deployment (Manual)
              run: |
                  echo "Production deployment would happen here"
                  echo "Build completed for commit: ${{ github.sha }}"
                  echo "Images tagged as: sha-${{ github.sha }}"
                  echo "To deploy manually:"
                  echo "   1. Configure kubectl for production cluster"
                  echo "   2. Run: helm upgrade --install cafe-management ./infrastructure/helm/cafe-management"
                  echo "   3. Update ArgoCD applications if needed"

    # Notify
    notify:
        name: Notify Build Status
        runs-on: ubuntu-latest
        needs: [test, security, build]
        if: always()

        steps:
            - name: Build Status Summary
              run: |
                  echo "## Build Summary"
                  echo "**Repository:** ${{ github.repository }}"
                  echo "**Branch:** ${{ github.ref_name }}"
                  echo "**Commit:** ${{ github.sha }}"
                  echo "**Actor:** ${{ github.actor }}"
                  echo "**Status:** ${{ job.status }}"
                  
                  if [ "${{ job.status }}" = "success" ]; then
                    echo "All checks passed!"
                  else
                    echo "Some checks failed. Please review the logs."
                  fi
